COMP: Fix tubeBaseIOPrintTest with option TubeTK_USE_LIBSVM disabled
This commit addresses the issue thrown when building TubeTK with
the option TubeTK_USE_LIBSVM set to off. See [1].
Since the include of itktubePDFSegmenterSVMIO.h depends on the value
of TubeTK_USE_LIBSVM, the print test should also meet the same
condition before being compiled.

[1]:/path/to/TubeTK-src/Base/IO/Testing/tubeBaseIOPrintTest.cxx:67:3:
    error: ‘PDFSegmenterSVMIO’ is not a member of ‘itk::tube’