COMP: ITKTubeTK: Fix MacOSX build error related to friendship declaration.
This commit fixes a regression introduced in d680b3f (STYLE: Move
implementation of CropFilter  into TukeTK/Base)

Error fixed by this commit was happening when building target "CropImage":

  TubeTK/Base/Filtering/itktubeCropImageFilter.h:156:24: error: a non-type template parameter cannot have type 'itk::Image'