COMP: Missing symbols in CompareImages executable
Addresses:

CompareImages.cxx:(.text.startup+0x29): undefined reference to
`itk::BMPImageIOFactoryRegister__Private()'
test/CompareTools/CMakeFiles/tubeCompareImages.dir/CompareImages.cxx.o:(.data.rel.ro+0x0):
undefined reference to `itk::BMPImageIOFactoryRegister__Private()'
test/CompareTools/CMakeFiles/tubeCompareImages.dir/CompareImages.cxx.o:(.data.rel.ro+0x8):
undefined reference to `itk::BioRadImageIOFactoryRegister__Private()'
test/CompareTools/CMakeFiles/tubeCompareImages.dir/CompareImages.cxx.o:(.data.rel.ro+0x10):
undefined reference to
`itk::Bruker2dseqImageIOFactoryRegister__Private()'
test/CompareTools/CMakeFiles/tubeCompareImages.dir/CompareImages.cxx.o:(.data.rel.ro+0x18):
undefined reference to `itk::GDCMImageIOFactoryRegister__Private()'
test/CompareTools/CMakeFiles/tubeCompareImages.dir/CompareImages.cxx.o:(.data.rel.ro+0x20):
undefined reference to `itk::GE4ImageIOFactoryRegister__Private()'
test/CompareTools/CMakeFiles/tubeCompareImages.dir/CompareImages.cxx.o:(.data.rel.ro+0x28):
undefined reference to `itk::GE5ImageIOFactoryRegister__Private()'
test/CompareTools/CMakeFiles/tubeCompareImages.dir/CompareImages.cxx.o:(.data.rel.ro+0x30):
undefined reference to `itk::GiplImageIOFactoryRegister__Private()'
test/CompareTools/CMakeFiles/tubeCompareImages.dir/CompareImages.cxx.o:(.data.rel.ro+0x38):
undefined reference to `itk::HDF5ImageIOFactoryRegister__Private()'
test/CompareTools/CMakeFiles/tubeCompareImages.dir/CompareImages.cxx.o:(.data.rel.ro+0x40):
undefined reference to `itk::JPEGImageIOFactoryRegister__Private()'
test/CompareTools/CMakeFiles/tubeCompareImages.dir/CompareImages.cxx.o:(.data.rel.ro+0x48):
undefined reference to `itk::JPEG2000ImageIOFactoryRegister__Private()'
test/CompareTools/CMakeFiles/tubeCompareImages.dir/CompareImages.cxx.o:(.data.rel.ro+0x50):
undefined reference to `itk::LSMImageIOFactoryRegister__Private()'
test/CompareTools/CMakeFiles/tubeCompareImages.dir/CompareImages.cxx.o:(.data.rel.ro+0x58):
undefined reference to `itk::MINCImageIOFactoryRegister__Private()'
test/CompareTools/CMakeFiles/tubeCompareImages.dir/CompareImages.cxx.o:(.data.rel.ro+0x60):
undefined reference to `itk::MRCImageIOFactoryRegister__Private()'
test/CompareTools/CMakeFiles/tubeCompareImages.dir/CompareImages.cxx.o:(.data.rel.ro+0x68):
undefined reference to `itk::MetaImageIOFactoryRegister__Private()'
test/CompareTools/CMakeFiles/tubeCompareImages.dir/CompareImages.cxx.o:(.data.rel.ro+0x70):
undefined reference to `itk::NiftiImageIOFactoryRegister__Private()'
test/CompareTools/CMakeFiles/tubeCompareImages.dir/CompareImages.cxx.o:(.data.rel.ro+0x78):
undefined reference to `itk::NrrdImageIOFactoryRegister__Private()'
test/CompareTools/CMakeFiles/tubeCompareImages.dir/CompareImages.cxx.o:(.data.rel.ro+0x80):
undefined reference to `itk::PNGImageIOFactoryRegister__Private()'
test/CompareTools/CMakeFiles/tubeCompareImages.dir/CompareImages.cxx.o:(.data.rel.ro+0x88):
undefined reference to `itk::StimulateImageIOFactoryRegister__Private()'
test/CompareTools/CMakeFiles/tubeCompareImages.dir/CompareImages.cxx.o:(.data.rel.ro+0x90):
undefined reference to `itk::TIFFImageIOFactoryRegister__Private()'
test/CompareTools/CMakeFiles/tubeCompareImages.dir/CompareImages.cxx.o:(.data.rel.ro+0x98):
undefined reference to `itk::VTKImageIOFactoryRegister__Private()'
clang: error: linker command failed with exit code 1 (use -v to see
invocation)